library(readr)
library(readxl)
keylol_3 <- read_excel("keylol-3.xlsx")
keylol_2 <- read_excel("keylol-2.xlsx")
keylol_1<- read_csv("keylol-1.csv")
lm1 <-lm(credit~BG+Re+OT+(Year+1),data = keylol_1) 
summary(lm1)
lm4 <-lm(UG~BG+Re+OT+(Year+1),data = keylol_1) 
summary(lm4)
lm2 <-lm(credit~BG+Re+OT+(Year+1),data = keylol_2) 
summary(lm2)
lm5 <-lm(UG~BG+Re+OT+(Year+1),data = keylol_2) 
summary(lm5)
lm3 <-lm(credit~BG+Re+OT+(Year+1),data = keylol_3) 
summary(lm3)
lm6 <-lm(UG~BG+Re+OT+(Year+1),data = keylol_3) 
summary(lm6)
#waste
library(MatchIt)
match_d <- matchit(credit~(Year+1)+BG+UG,data = data1,method = "nearest",ratio=1)